### PR TITLE
Calculator modified \  fix: issue #5

### PR DESCRIPTION
**Pull request by Akshaysrajan**

### CODE REVIEW

**Comment by Akshaysrajan** [comment]
deployed link https://akshaysrajan.github.io/Mini-Projects/Calculator

**Comment by Akshaysrajan** [comment]
Can you please resolve this

**Comment by Akshaysrajan** [comment]
Hello @Axe-Pearl any updation regarding your excluded repo, is it fixed ?
should i raise a PR again to resolve it in hacktoberfest website

**Comment by Axe-Pearl** [comment]
**Hey @Akshaysrajan, Sorry for the inconvenience.
Wait this repository is excluded, before I merge any pull request, I am resolving the issue.
Be Patient, and keep tuned, the problem will be fixed soon, I am closing the issue for a temporary time
You will be notified when problem will be fixed
Thanks for your cooperation**

**Pull request closed without merging**
